import type { ChatMessage, OptionsRecommendation, RecommendationLeg } from "@/types"

export const mockLeg: RecommendationLeg = {
  id: "leg-1",
  leg_order: 1,
  action: "buy",
  option_type: "call",
  strike: 150,
  contracts: 1,
  premium: 5.0,
  bid: 4.8,
  ask: 5.2,
  implied_volatility: 0.28,
  open_interest: 5000,
  volume: 1000,
  delta: 0.52,
  gamma: 0.03,
  theta: -0.05,
  vega: 0.12,
}

export const mockSellLeg: RecommendationLeg = {
  id: "leg-2",
  leg_order: 2,
  action: "sell",
  option_type: "call",
  strike: 155,
  contracts: 1,
  premium: 2.5,
  bid: 2.3,
  ask: 2.7,
  implied_volatility: 0.29,
  open_interest: 3000,
  volume: 600,
  delta: 0.35,
  gamma: 0.025,
  theta: -0.04,
  vega: 0.1,
}

export const mockRecommendation: OptionsRecommendation = {
  id: "rec-1",
  message_id: "msg-1",
  session_id: "sess-1",
  ticker: "AAPL",
  strategy_type: "bull_call_spread",
  strategy_name: "Bull Call Spread",
  confidence_score: 75,
  strategy_reasoning: "Bullish on AAPL",
  strike_reasoning: "Near ATM",
  expiration_reasoning: "30 DTE balance",
  entry_conditions: "Hold above 148",
  exit_conditions: "50% profit",
  adverse_scenario: "Below 140",
  max_profit: 700,
  max_loss: -300,
  breakeven_prices: [103.0],
  capital_required: 300,
  margin_requirement: 0,
  risk_reward_ratio: 2.33,
  risk_score: 4,
  has_unlimited_risk: false,
  has_assignment_risk: false,
  has_high_gamma: false,
  has_volatility_sensitivity: false,
  spot_price_at_analysis: 150.0,
  expiration_date: "2026-04-17",
  days_to_expiry: 30,
  legs: [mockLeg, mockSellLeg],
  decision: null,
  created_at: "2026-03-07T00:00:00Z",
}

export const mockUserMessage: ChatMessage = {
  id: "msg-user-1",
  session_id: "sess-1",
  role: "user",
  content: "Give me a strategy for AAPL",
  has_recommendation: false,
  created_at: "2026-03-07T00:00:00Z",
  recommendations: [],
}

export const mockAssistantMessage: ChatMessage = {
  id: "msg-asst-1",
  session_id: "sess-1",
  role: "assistant",
  content: "Here's a **bull call spread** for AAPL.",
  has_recommendation: true,
  created_at: "2026-03-07T00:01:00Z",
  recommendations: [mockRecommendation],
}
